# Generated by Django 3.1 on 2020-08-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=130, verbose_name='user email')),
                ('user_name', models.CharField(max_length=255, verbose_name='username')),
                ('user_signup_date', models.DateTimeField(verbose_name='date of signup')),
            ],
        ),
    ]
