# Generated by Django 3.1 on 2020-08-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserRegistrForm',
        ),
    ]
